### PR TITLE
About page edits

### PR DESCRIPTION
**Pull request by cmahony**
@joeyklee, this is my first foray into the github flow. i made a couple of necessary changes to the about page and hopefully this pull request is what you need to move forward with the changes. any comments on how to do this better are appreciated.

### CODE REVIEW

**Comment by joeyklee** [comment]
@cmahony the changes look harmess to me, but I'm wondering, have you been able to run the app locally from your computer using the instructions [here](https://github.com/joeyklee/bec-explorer/blob/master/SETUP.md)?

**Comment by cmahony** [comment]
Hey joey, i installed node.js, but stalled out there. when i typed "cd bec-explorer" into the node.js interface i got an error message. sorry, i'm pretty frickin hopeless at this type of thing. this might not be the week for you to hold my hand through the github flow so feel free to drop this and we can pick it up when you get back from Kenya. 

image

**Comment by joeyklee** [comment]
@cmahony try:
1. change your directory in your command line: `cd` stands for `change directory`

```
cd path/to/the/correct/bec-explorer
```
1. run node

```
node server.js
```

let me know if this helps to clarify

**Comment by joeyklee** [comment]
and actually instead of running the node.js commandline window, try using your normal `command line`.

**Comment by joeyklee** [comment]
see: http://blog.teamtreehouse.com/install-node-js-npm-windows

**Comment by cmahony** [comment]
so presumably i have to create a directory called bec-explorer and then download the server.js file from github to this local directory. is it the server.js file on the root directory in github? anything else? am i totally off track? you might need to really spell this out for me.

**Comment by joeyklee** [comment]
Let me know if this helps to clarify: https://youtu.be/YBGxRQSui1Y

**Comment by cmahony** [comment]
awesome. i'll work through that. thanks a million!!

**Comment by joeyklee** [comment]
Since we made a bunch of page edits, I'm going to close this pull request rather than integrate it. Now that we have a good workflow, we should be ok from now on.

**Pull request closed without merging**
